services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: project-backend

  client:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: project-frontend

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: project-db